name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: docker login for Github
        uses: docker/login-action@v1
        with:
          registry:  ghcr.io
          username: carljmosca
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/carljmosca/myq-monitor/myq-monitor:latest